### ISSUE TITLE
verken testen met Q Edison

### ISSUE THREAD

**Issue by Murkrage** [Murkrage/UbiPsych#1]
* ontdek de Q Edison als prototyping platform
  * wat kan hij zoal?
    * welke zintuigen heeft een Q Edison (afferent, inputs)
    * welke actuatoren? (efferent, outputs)
    * hoe kan ik programmeren?
  * welke waarneembare gedragingen kan ik bij mijn doelgroep opwekken met de Q Edison? (Elke student ten minste 5)
    * welke zintuigen en actuatoren (inputs, outputs, efferent, afferente stromen) kan ik bij mijn doelgroep aanspreken met een Q Edison?

## Definition of done

* lijst van inputs en outputs van de Q Edison
* lijst van bouwstenen voor flows met parameters
* lijst van voorbeeld cases in volgorde van informativiteit

**Comment by Murkrage** [comment]
**Input:**
2 infrarood sensoren (links en rechts)
geluidsensor / klapsensor
line-tracking sensor

**Output:**
LED lichtjes
Buzzer
Gemotoriseerde wieltjes

**Buttons:**
Record, Stop, Play, On/Off

**Programmeren:**
Drag-and-drop elementen in edwareapp.com. Je gebruikt basis logica elementen om een programma te maken die je kan laden op de Edison Robot. Hierbij maak je gebruik van onder andere Loops, If/Else statements, triggers (input) en actions (output). Zonder een regel code kan je dit makkelijk in elkaar zetten.

**Comment by Shatango** [comment]
5 gedragingen die we kunnen opwekken bij de doelgroep met Q Edison. 

- Door bijvoorbeeld geluid op te vangen kan er gemeten worden of je afgeleid bent of niet. 
Bijvoorbeeld als je je verveeld ga je op de tafel tikken of hoor je een zucht waarmee je bijvoorbeeld iemand zijn concentratiespan kan meten en zo een muziekje af te laten spelen.

- Doormiddel van irritante geluiden te kijken of je de doelgroep alarmeren van de status van de situatie (Met milde waarschuwing vooraf).

- Doormiddel van een lampje kan je bijvoorbeeld aan het niveau van het geluid zien hoe afgeleid iedereen is.

- Als je niet meer op je plek bent dat ie je dan volgt.

- Doormiddel van het toetsenbord gebruik te meten of je bezig bent.

- Ogen tracken met webcam om te kijken waar je op dat moment op focust. (of dat je wegloopt)

- Periodes aangeven door events licht/geluid
